% Run nfblab for any headset
% --------------------
addpath(fullfile(pwd, '..','..'));

nChan = 32; % number of channels
sRate = 128; % sampling rate

% The program will search for an LSL stream of type EEG
% It will then control a curve (simpleplot) based on the theta
% power of the first channel (default value for parameter 'freqprocess').
% See nfblab_setfield for all available options.

% tested with Psychtoolbox-3-3.0.19.0

options = { ...
    'streamFile'             fullfile('..', 'basic_offline', 'eeglab_data.set') ...
    'chans'                  [1:nChan] ...
    'chanmask'               eye(nChan) ...
    'srate'                  sRate ...
    'windowSize'             sRate ...
    'runmode'               'trial' ...
    'pauseSecond'            0 ...
    'badchanFlag'            false ...
    'icaFlag'                false ...
    'asrFlag'                false ...
    'freqrange'              { [4 8] [8 12] [8 10] [10 12] [18 22] [4 10] [12 15] [20 30] } ...
    'feedbackMode'           'dynrange' ...
    'funcinit'               'nfblab_feedback_psychootoolbox_init' ...
    'funcfeedback'           'nfblab_feedback_psychootoolbox_process' ...
    'funcend'                'nfblab_feedback_psychootoolbox_end' ...
    };

nfblab_process(options{:});
