% Run nfblab for any headset which has LSL
% ----------------------------------------
addpath(fullfile(pwd, '..','..'));
nChan = 4; % number of channels
sRate = 250; % sampling rate

% The program will search for an LSL stream of type EEG
% It will then control a curve (simpleplot) based on the theta
% power of the first channel (default value for parameter 'freqprocess').
% See nfblab_setfield for all available options.

options = { ...
    'chans'                  1:nChan ...
    'chanmask'               eye(nChan) ...
    'srate'                  250 ...
    'runmode'               'trial' ...
    'pauseSecond'            0.2 ...
    'badchanFlag'            false ...
    'icaFlag'                false ...
    'asrFlag'                false ...
    'freqrange'              { [4 8] [8 12] [8 10] [10 12] [18 22] [4 10] [12 15] [20 30] } ...
    'simplePlot'             true ...
    'feedbackMode'           'dynrange' };

nfblab_process(options{:});
