% This script implement a simple GUI for NeuroFeedbackLab
% By default it runs with an offline file, but toggle the
% flag to false below to run it with LSL

testOffline = true; % switch to false to run with LSL

addpath(fullfile(pwd, '..','..'));

nChan = 4; % number of channels
sRate = 128; % sampling rate

simpleApp;
drawnow
    
options = { ...
    'chans'                  1:nChan ...
    'chanmask'               eye(nChan) ...
    'srate'                  sRate ...
    'windowSize'             sRate ...
    'runmode'               'trial' ...
    'pauseSecond'            0.2 ...
    'badchanFlag'            false ...
    'icaFlag'                false ...
    'asrFlag'                false ...
    'freqrange'              { [4 8] [8 12] [18 22] [22 30] } ...
    'feedbackMode'           'dynrange' ...
    'checkglobalmsg'         'messagevar'   };

% fist command
if ~testOffline
    disp('Trying to connect to LSL...')
    messagevar.command = 'lslconnect';
    messagevar.options = [];
else
    filePath = fileparts(which('eeglab'));
    options = [ {'streamFile' fullfile(filePath, 'sample_data', 'eeglab_data.set') } options];
end

nfblab_process(options{:});
